# Generated by Django 5.1.8 on 2025-05-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=6),
        ),
        migrations.AddField(
            model_name='appointment',
            name='problem_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='qr_Code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
