# Generated by Django 5.1.8 on 2025-05-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_gender_appointment_problem_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=6, null=True),
        ),
    ]
