# Generated by Django 5.2 on 2025-05-19 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_medication_frequency_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='prescription',
        ),
        migrations.AddField(
            model_name='medication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(default='1 tablet', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration',
            field=models.CharField(default='14 days', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescribed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_items', to='core.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='prescribed_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medication_items', to='core.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(choices=[('once_daily', 'Once Daily'), ('twice_daily', 'Twice Daily'), ('three_daily', 'Three Times Daily'), ('four_daily', 'Four Times Daily'), ('as_needed', 'As Needed')], max_length=50),
        ),
    ]
