# Generated by Django 5.2 on 2025-05-19 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorrating'),
        ('core', '0003_remove_medication_dosage_and_more'),
    ]

    operations = [
    ]
