# Generated by Django 5.2 on 2025-05-20 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250519_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.appointment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.prescription'),
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_scheduled', 'Appointment Scheduled'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_canceled', 'Appointment Canceled'), ('appointment_rescheduled', 'Appointment Rescheduled'), ('appointment_completed', 'Appointment Completed'), ('prescription_created', 'Prescription Created'), ('prescription_updated', 'Prescription Updated'), ('medication_reminder', 'Medication Reminder')], default='appointment_reminder', max_length=50),
        ),
    ]
