# Generated by Django 5.2 on 2025-05-22 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_appointment_notification_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='prescribed_by',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='prescribed_to',
        ),
    ]
