# Generated by Django 5.2 on 2025-05-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_appointment_notification_prescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
